version: '3.8'

services:
  test-postgres:
    image: postgres:15-alpine
    container_name: omiseyasan_test_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: omiseyasan_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d omiseyasan_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=1000m